##############################################
# Traefik Static Configuration - Development #
##############################################

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard (insecure for dev)
api:
  dashboard: true
  insecure: true
  debug: false

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "portyard_sail"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Logging
log:
  level: ERROR
  format: common
